name: Tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this branch
        uses: actions/checkout@master
      - name: Install node modules
        run: npm install
      - name: Run the linter
        run: npm run lint
      - name: Run the tests
        run: npm run test
      - name: Run code coverage
        run: bash <(curl -s https://codecov.io/bash)
